### ISSUE TITLE
An await doesn't wait the end and return of a function

### ISSUE THREAD

**Issue by Kaos1337** [yortus/asyncawait#20]
Hi,
I need help, I'm using this library and this is an example with the problem that I've encountered:

// message is an object not used in this example, uri is the download url (http://site.com/file.png), name is the candidate name of save

```
var foo = async(function(message, uri, name) {
    var validName = await(checkFile(name));     <-- the function checkFile checks the candidate name and change it if already used on the disk.
    console.log("valid name: " + validName);      <-- a print just to check, yes, the var "validName" is ok, contains the new name of the file.
    var downloadedName = await(downloadFile(uri, validName));    <-- the function downloadFile download the file from the url and save it with the new name.
    console.log("Downloaded name: " + downloadedName);  <-- the var downloadedName isn't up to date, print undefined.
    return true;  <-- don't care, it's just a test.
});
```

This is the function downloadFile:
```
function downloadFile(uri, filename) {
    console.log("[downloadFile] definitiveName: " + filename);        <--- print correctly the definitive name
    request(uri).pipe(fs.createWriteStream(filesFolder + filename)).on('close', function(err){
        if(err) throw console.log(err);
        else {
            console.log("[downloadFile] Downloaded: " + filename);       <--- print correctly the definitive name
            return filename;          <-- the return of the function
        }
    });
}
```

What happen in console:
Valid name: theNameOfTheFile.png
[downloadFile] definitiveName: theNameOfTheFile.png
Downloaded name: undefined
[downloadFile] Downloaded: theNameOfTheFile.png

The question is: why the second await() doesn't wait the end and return of the function?
Regards.

**Comment by yortus** [comment]
Hi @Kaos1337,

The `downloadFile()` function is not [awaitable](https://github.com/yortus/asyncawait#what-works-with-await) in its current form. Try this:

```javascript
function downloadFile(uri, filename) {
    return new Promise(function (resolve, reject) {
        console.log("[downloadFile] definitiveName: " + filename); <--- print correctly the definitive name
        request(uri)
        .pipe(fs.createWriteStream(filesFolder + filename))
        .on('close', function(err) {
            if(err) {
                reject(err);
            }
            else {
                console.log("[downloadFile] Downloaded: " + filename); <--- print correctly the definitive name
                resolve(filename); <-- the return of the function
            }
        });
    });
}
```

Explanation: The original `downloadFile()` function runs the first `console.log`, then starts the asynchronous `request(uri)` operation, then immiediately returns `undefined`. This `undefined` is what is being passed to `await` in the other function you provided. I have wrapped the code inside `downloadFile` in a promise, and returned the promise. The promise gets resolved once the file is downloaded. `await` receives this promise and waits for it to resolve before continuing.

BTW wrap your code in triple backticks to make it easier to read in github comments, like so:

    ```
    function foo() { ... }
    ```

**Comment by Kaos1337** [comment]
Thank you, works!
I've also corrected my first message as you suggested.
