### ISSUE TITLE
the "asyncawait.d.ts" file can not be installed by tsd, so it is inconvenient to install it

### ISSUE THREAD

**Issue by plantain-00** [yortus/asyncawait#24]
http://definitelytyped.org/tsd/

**Comment by yortus** [comment]
Hi @plantain-00,

I've just made a few updates, including addressing this issue. As of TypeScript 1.6, tsc does proper node-style module lookup and finds the `asyncawait` typings automatically. You just need to:

1. install `asyncawait` normally into your project, ie `npm install asyncawait --save`
2. require it with `import {async, await} from 'asyncawait';`

Going forward `tsd` and DefinitelyTyped will be just for typings for non-TypeScript modules.

Note that the module lookup of tsc 1.6beta is sill limited, so if you do `import async = require('asyncawait/async');` it won't find the typing. Hopefully they fix that soon but it's not a show stopper given the alternate syntax above works fine.
