### ISSUE TITLE
async to callback

### ISSUE THREAD

**Issue by yaronn** [yortus/asyncawait#26]
I have a library written using the async/await pattern. I try to consume it from a library which uses callbacks. Here is a sample code:

    var async = require('asyncawait/async');
    var await = require('asyncawait/await');
    var Promise = require('bluebird');

    var foo = async (function() {
        var resultA = await (Promise.promisify(bar));
        return 111;
    })

    function bar(callback) {
      setTimeout(callback, 2000)
    }

    function moo() {
      var f = async.cps(foo)

      f(function(err, res) {
        console.log(res)
      })

    }

    moo()

I expected console.log to print 111 but instead it prints:

    { _bitField: 0,
      _fulfillmentHandler0: undefined,
      _rejectionHandler0: undefined,
      _progressHandler0: undefined,
      _promise0: undefined,
      _receiver0: undefined,
      _settledValue: undefined }

btw if I inline foo in the async.cps line it works (but this is not an option since its an external library).

Any idea?

**Comment by yaronn** [comment]
title

**Comment by yortus** [comment]
Hi @yaronn, try this:

```javascript
var async = require('asyncawait/async');
var await = require('asyncawait/await');
var Promise = require('bluebird');

var foo = async.cps (function() {
    var resultA = await (Promise.promisify(bar));
    return 111;
})

function bar(callback) {
  setTimeout(callback, 2000)
}

function moo() {

  foo(function(err, res) {
    console.log(res)
  })

}

moo()
```

Another suggestion is to call `Promise.promisify` just once rather than every time `foo` gets called. It's not an error but its just computing the same thing each time.

**Comment by yaronn** [comment]
thanks but foo() is from a standalone library (written by my colleague). Is there a way to do it without changing it? I write a callback style library (moo) and want to consume an async/await style library without changing it.
If change to foo is must, what are the implications to other methods that already call foo (from other modules which use the async/await pattern or from the foo module itself)?

**Comment by yortus** [comment]
Ah okay, then you don't have to change `foo`. So `foo` is just a function that returns a promise, and you want a function that takes a callback. You can either use something like [nodeify](https://www.npmjs.com/package/nodeify), or wrap it yourself like this:

```javascript
var fooCps = async.cps (function() {
    return await(foo());
})
```

**Comment by yaronn** [comment]
thanks @yortus  this works!

**Comment by yortus** [comment]
No probs
