### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by edwardsmarkf** [yortus/asyncawait#30]
hello -   (newbie here)

having become an excellent code "indentor" with multiple nested async functions, i am most eager to try out asyncawait.

i attempted to do a simple install as per the instructions i read:

 npm install asyncawait ;

and here is my error log below  - i read where it said to contact the author - i hope this is the correct forum.

http://edwardsmark.com/asyncawaitIssue/npm-debug.log

> alias  nodejs=node ;
> nodejs -v
v4.2.3
> npm -v
2.5.1
>  npm owner ls fibers
laverdet <marcel.npm@laverdet.com>

thank you very much.

**Comment by yortus** [comment]
Hi @edwardsmarkf,

It looks like a problem installing [node-fibers](https://github.com/laverdet/node-fibers/) (See line 535 in your debug log). Node-fibers is a binary (C/C++) module, so it has added requirements for building. Please check with that project for build requirements for your system, and open an issue there if you still have problems.

**Comment by edwardsmarkf** [comment]
thank you - it turns out fibers wont install for me.  i contacted marcel.npm[at]laverdet[dot]com for assistance.
