### ISSUE TITLE
Not working on nw.js

### ISSUE THREAD

**Issue by noorkaximi** [yortus/asyncawait#53]
I am trying to use it on node-webkit (nw.js) but when I import it. it throws an error 
my code.
`var async = require('asyncawait/async');
var await = require('asyncawait/await');`
Here is the error
> module.js:482 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> \\?\E:\ZeroKit\webkit-v0.13\ZeroKitFinal\node_modules\fibers\bin\win32-x64-48\fibers.node

**Comment by yortus** [comment]
This is an issue with [node-fibers](https://github.com/laverdet/node-fibers). There isn't much asyncawait can do about this. Hopefully https://github.com/laverdet/node-fibers/issues/271 might be of some help.
