### ISSUE TITLE
Error: await functions, yield functions, and value-returning suspendable functions.

### ISSUE THREAD

**Issue by igunjan** [yortus/asyncawait#54]
I'm trying to use these method in my project but it's give me error when call `await`. Please check follow details.

code structure is : 

    var await = require('asyncawait/await');
    fiber(function() {
            Promise
                .then(() => {
                    var settingParameter = await (require('./settingObjects_2.js')(req));
                })
            });

settingObjects_2.js

    module.exports = function(){
    }

>  ERROR : 
An unrelayed rejection happens:
Error: await functions, yield functions, and value-returning suspendable functions may only be called from inside a suspendable function. 
    at await (/home/snow22/workspace/svn_checkout/MIXTTS/jira/TTS-103/node_modules/asyncawait/src/await/makeAwaitFunc.js:20:19)

**Comment by yortus** [comment]
@igunjan you can only call `await` from inside a function that is wrapped inside an `async` call. E.g.:

```js
var async = require('asyncawait/async');
var await = require('asyncawait/await');

var foo = async (function () {
    var x = await (someOtherAsyncFunction());
    return x;
});

foo().then(...)

```
