### ISSUE TITLE
setTimout example?

### ISSUE THREAD

**Issue by Jodes81** [yortus/asyncawait#55]
Sorry for the basic question, how could asyncawait be used for the native `setTimeout` in Node? 

I presume it would still have to use thunkify? If so, how might that be done?

From the examples I can see delay examples with bluebird, but I want to explore alternatives - partly for learning, and partly to avoid larger libraries that I don't understand (yet).

Really appreciated

**Comment by yortus** [comment]
@Jodes81, asyncawait is based around promises so with something callback-based like `setTimeout` you must wrap it in a promise-returning function first to be able to use it. However it doesn't matter which Promise library you use, and ES6 Promises will do fine.

The wrapped version and a little test function that calls it would look something like this:

```js
/** Returns a promise that is resolved after `ms` milliseconds */
function delay(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    });
}

let test = async (() => {
    console.log('starting...');
    await (delay(500));
    console.log('after 0.5 sec');
    await (delay(500));
    console.log('after 1 sec');
});
```

**Comment by yortus** [comment]
Let me know if you still have questions, happy to help.
