### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by Jakobud** [yortus/asyncawait#56]
I have the following basic code

```
'use strict'

const async = require('asyncawait/async');
const await = require('asyncawait/await');
const got = require('got')

async function mytest () {
  const options = {}
  let response = await got.get('https://www.google.com', options)
  console.log(response)
}
mytest()
```

This uses the [got](https://github.com/sindresorhus/got) httprequest library to pull a webpage and print out the response. I get the following error:

```
async function requestNewAccessToken2 (ocapi) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I feel like there is some basic thing I'm misunderstanding here. I'm using Node 6.7.0. But the `asyncawait` library should work fine in this version right?

**Comment by Seikho** [comment]
You'll need to:
```
const mytest = async(() => {
 const options = {}
  let response = await(got.get('https://www.google.com', options))
  console.log(response)
})
```
`asyncawait/async` and `asyncawait/await` are functions.

**Comment by yortus** [comment]
Thanks @Seikho. @Jakobud does that answer your question?

The syntax you wrote is valid if you are using [ES2017 async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), but you'll still need a transpiler for that. This lib is much older and achieves the same runtime semantics using just functions.

**Comment by Jakobud** [comment]
Ah okay the ES2017 syntax is what my issue was. Thank you. I have changed it to this:

```
'use strict'

const async = require('asyncawait/async');
const await = require('asyncawait/await');
const got = require('got')

const mytest = async(() => {
  const options = {}
  let response = await(got.get('https://www.google.com', options))
  return response
})

let value = mytest
console.log(value)
```

Now, my output is just

```
[Function: f0]
```

I would expect it to be printing out the http response for the call to google.com. I also tried doing

```
let value = await(mytest)
console.log(value)
```

But then I get

```
Error: await functions, yield functions, and value-returning suspendable functions may only be called from inside a suspendable function.
```

**Comment by yortus** [comment]
`mytest` is a function that returns a `Promise` (just like an ES2017 async function does).

So at the outermost level of code you'll need to use `then` to get at the final result, like this:

```js
mytest().then(() => {
    console.log(value);
});
```

**Comment by Jakobud** [comment]
I'm really confused as to the purpose of `async/await` then if I would just write the same function without it:

```
const mytest = () => {
  return new Promise((resolve, reject)=>{
    setTimeout(()=>{
      resolve('hello world')
    }, 2000)
  })
}

mytest().then((value) {
  console.log(value)
})
```

I guess I was under the impression that the `async/await` allows you to return value from a Promise-type of function where the value you get is what was resolved in that Promise. I feel like I'm missing something really fundamental about this.

**Comment by yortus** [comment]
> I was under the impression that the async/await allows you to return value from a Promise-type of function where the value you get is what was resolved in that Promise.

That's exactly what it allows you to do *inside* the body of the async function. It may not seem much of an improvement for trivial asynchronous code, but it makes a big difference when you combine non-trivial control flow with asynchronous operations.

Say for example, something like attempting an asynchronous operation with several retry attempts if the operation fails. Inside an async function, you could do that with an ordinary `for` loop and a `try/catch` block. Threading the same logic together with promises alone is much more challenging. There are control flow libs to help with this, but the point is that with async/await you don't need these helper libs, since you can just use ordinary control flow statements. The end result is also easier to read and maintain IMO.
