### ISSUE TITLE
Extra parentheses?

### ISSUE THREAD

**Issue by mitchellporter** [yortus/asyncawait#60]
I've seen a lot of native `async/await` code that looks like this:

```
const makeRequest = async () => {
  var result = await callAPromise()
  return result;
}
```

Same example but without the arrow function:
```
async function makeRequest() {
  var result = await callAPromise();
  return result;
}
```

I was just playing around with this package and noticed that if I try to write async/await code like the above, I always get  an `unexpected token` error for the `function` keyword. I then noticed in all of your examples that you wrap both `async` and `await` in extra parentheses:

```
var countFiles = async (function (dir) {
    var files = await (fs.readdirAsync(dir));
    var paths = _.map(files, function (file) { return path.join(dir, file); });
    var stats = await (_.map(paths, function (path) { return fs.statAsync(path); })); // parallel!
    return _.filter(stats, function (stat) { return stat.isFile(); }).length;
});
```
I just wanted to make sure I'm understanding correctly that this is the only way it works. Not trying to sound negative but I realized that if you were to use this, and then later wanted to switch to native `async/await`, that I'd be stuck with `IIFE's` everywhere when not needed.

Why is the `IIFE` necessary? Just curious and looking to learn more about your choices and implemenetation. Thanks.

**Comment by yortus** [comment]
Hi @mitchellporter, 

This is a userland implementation of async/await semantics, where `async` and `await` are just functions. That's the reason for the parentheses: function calls require parentheses around arguments. There are no IIFEs, but the async function expects a function expression as its argument.

The deeper reason is that this library has been around for 3 years, well before there was native async/await in JavaScript. This was as close as you could get to async/await in JS back then without a transpiler. These days, ES2017 async/await is supported with transpilers like Babel and TypeScript, and is very nearly in stable Node.js, so there's not much reason for new projects to use this library.

I should update the README to reflect the above point so its clear to other who come across this. Thanks for the reminder!

**Comment by mitchellporter** [comment]
@yortus Thanks for the detailed response :)
