### ISSUE TITLE
Using a for loop

### ISSUE THREAD

**Issue by samcov** [yortus/asyncawait#62]
I didn't see any examples using a for loop. Is it as simple as wrapping the for loop as below,

```js
var foo = async (function() {
    for(var i=0; i < 10; i++)
    {
         var v= await (doSomething(30));
    }
});
```

**Comment by yortus** [comment]
@samcov yes, that looks right.

**Comment by samcov** [comment]
Thanks, we need this on older Node versions that we can't upgrade.
