### ISSUE TITLE
Not an issue, just a thank you.

### ISSUE THREAD

**Issue by tokunbo** [yortus/asyncawait#68]
:1st_place_medal: 

I know nodejs these days has built-in await/async, but I hope you're still maintaining your version.
It's basically impossible to do the following with nodejs's built-in:
```
pikachu@POKEMONGYM ~/tmp3/nodejsSeleniumWrapper $ cat ./asynNodeREPL.js 
var repl = require('repl').start(),
  async = require('asyncawait/async'),
  await = require('asyncawait/await'),
  original_eval = repl.eval;
repl.context.async = async;
repl.context.await = await;
repl.eval = async(function(code, context, filename, callback) {
  original_eval(code, context, filename, callback);
});

pikachu@POKEMONGYM ~/tmp3/nodejsSeleniumWrapper $ node ./asynNodeREPL.js 
> await(new Promise(function(resolve) { console.log(new Date()); setTimeout(function() { resolve(new Date());},5000); }));
2018-05-05T04:25:13.329Z
2018-05-05T04:25:18.336Z
> 
```
Unlike nodejs's built-in, your version seems to allow any function that is a call-tree descendant of an async-function to be able to use await() and that makes me be able to do all kinds of cool stuff abstracting away promises or even needing to type await all over the place if the function I'm calling already does it internally. And being able to await in the REPL this easily is a big deal imho.

**Comment by yortus** [comment]
Thanks @tokunbo, I appreciate your kind words!

This library was really helpful before JavaScript had async/await. And even today, what you say about shallow vs deep async/await is still an advantage, so at one point I though to re-position this library to emphasize this difference. However I think using native async/await, despite its limitations, is the better way to go to create maintainable and interoperable code. So I don't actively work on this anymore.

However if other people still find it useful, then of course it should stick around. It probably does need some updates to the README to clarify where this stands vs native async/await, and also to support new environments (eg `await` can no longer be used as an indentifier in ES6 modules).
